# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-04 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='bank_details',
            new_name='ifsc',
        ),
    ]
